FROM node: 20.12.1 AS development

WORKDIR /todoapp/src/app

COPY package*.json ./
COPY tsconfig.build.json ./
COPY tsconfig.json ./

RUN npm ci
RUN npm run build

EXPOSE 3000

FROM node: 20.12.1 AS production

ARG NODE_ENV = production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /todoapp/src/app

COPY --from=development /todoapp/src/app .

EXPOSE 3000

CMD ["node", "dist/main"]
